apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-tls
  namespace: pki-layer3
spec:
  secretName: server-tls
  issuerRef:
    name: workload-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: server.pki-layer3.svc.cluster.local
  dnsNames:
    - server.pki-layer3.svc.cluster.local
    - server.pki-layer3
    - server
  subject:
    organizations:
      - pki-poc
  duration: 1h
  renewBefore: 30m
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
